In [106]:
import pandas as pd
import numpy as np

In [107]:
obje = pd.Series(np.arange(5), index = ["a","b","c","d","e"])
obje

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [108]:
obje.c

np.int64(2)

In [109]:
obje["c"]

np.int64(2)

In [110]:
obje[:3]

a    0
b    1
c    2
dtype: int64

In [111]:
obje[::2]

a    0
c    2
e    4
dtype: int64

In [112]:
obje[["a","c"]]

a    0
c    2
dtype: int64

In [115]:
obje[obje<2]

a    0
b    1
dtype: int64

In [116]:
obje["a":"c"]   #including final value

a    0
b    1
c    2
dtype: int64

In [117]:
obje["b":"c"]=5
obje

a    0
b    5
c    5
d    3
e    4
dtype: int64

In [119]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                    index=["bursa","ankara","rize","istanbul"],
                    columns=["one","two","three","four"])
data

          one  two  three  four
bursa       0    1      2     3
ankara      4    5      6     7
rize        8    9     10    11
istanbul   12   13     14    15

In [120]:
data[["one","three"]]

          one  three
bursa       0      2
ankara      4      6
rize        8     10
istanbul   12     14

In [122]:
data[:3]   #final index not included

        one  two  three  four
bursa     0    1      2     3
ankara    4    5      6     7
rize      8    9     10    11

In [123]:
data[data["four"]>5]

          one  two  three  four
ankara      4    5      6     7
rize        8    9     10    11
istanbul   12   13     14    15

In [ ]:
#iloc for numbers
#loc for tags

In [124]:
data.iloc[1]  # index 1

one      4
two      5
three    6
four     7
Name: ankara, dtype: int64

In [125]:
data.iloc[1,[1,2,3]]  #index 1, column 1,2,3

two      5
three    6
four     7
Name: ankara, dtype: int64

In [126]:
data.iloc[[1,3],[1,2,3]]

          two  three  four
ankara      5      6     7
istanbul   13     14    15

In [128]:
data.loc["rize", ["one","two"]]

one    8
two    9
Name: rize, dtype: int64

In [139]:
data.loc[:"rize","four"]

bursa      3
ankara     7
rize      11
Name: four, dtype: int64

In [130]:
#important methods

In [138]:
data2 = data.reindex(["rize","istanbul","bursa","ankara","nigde"])
data2

           one   two  three  four
rize       8.0   9.0   10.0  11.0
istanbul  12.0  13.0   14.0  15.0
bursa      0.0   1.0    2.0   3.0
ankara     4.0   5.0    6.0   7.0
nigde      NaN   NaN    NaN   NaN

In [143]:
number = ["four", "one", "five"]
data.reindex(columns=number)

          four  one  five
bursa        3    0   NaN
ankara       7    4   NaN
rize        11    8   NaN
istanbul    15   12   NaN

In [140]:
s = pd.Series(["blue", "red", "pink"], index=[0,2,3])
s

0    blue
2     red
3    pink
dtype: object

In [141]:
s.reindex(range(6), method = "ffill")

0    blue
1    blue
2     red
3    pink
4    pink
5    pink
dtype: object

In [146]:
new_s = s.drop(2)
new_s

0    blue
3    pink
dtype: object

In [147]:
s.drop([0,3])

2    red
dtype: object

In [148]:
data3 = pd.DataFrame(np.arange(16).reshape(4,4), 
                     index = ["ali" ,"efe", "can", "nur"],
                     columns = list("ABCD"))
data3

      A   B   C   D
ali   0   1   2   3
efe   4   5   6   7
can   8   9  10  11
nur  12  13  14  15

In [150]:
data3.drop(["ali", "efe"])

      A   B   C   D
can   8   9  10  11
nur  12  13  14  15

In [151]:
# axis = 1  or axis="index"    To delete a column
# axis = 0  or axis="columns"  To delete a row

In [153]:
data3.drop("A",axis=1)

      B   C   D
ali   1   2   3
efe   5   6   7
can   9  10  11
nur  13  14  15

In [154]:
data3.drop("ali",axis=0)

      A   B   C   D
efe   4   5   6   7
can   8   9  10  11
nur  12  13  14  15

In [155]:
data3.mean()

A    6.0
B    7.0
C    8.0
D    9.0
dtype: float64

In [159]:
data3.mean(axis="columns")

ali     1.5
efe     5.5
can     9.5
nur    13.5
dtype: float64